// Code generated by goctl. DO NOT EDIT.
// Source: sts.proto

package server

import (
	"context"

	"github.com/xh-polaris/sts-rpc/internal/logic"
	"github.com/xh-polaris/sts-rpc/internal/svc"
	"github.com/xh-polaris/sts-rpc/pb"
)

type StsRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStsRpcServer
}

func NewStsRpcServer(svcCtx *svc.ServiceContext) *StsRpcServer {
	return &StsRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *StsRpcServer) GetUserCosSts(ctx context.Context, in *pb.GetUserCosStsReq) (*pb.GetUserCosStsResp, error) {
	l := logic.NewGetUserCosStsLogic(ctx, s.svcCtx)
	return l.GetUserCosSts(in)
}
