// Code generated by goctl. DO NOT EDIT.
// Source: sts.proto

package server

import (
	"context"

	"github.com/xh-polaris/sts-rpc/internal/logic"
	"github.com/xh-polaris/sts-rpc/internal/svc"
	"github.com/xh-polaris/sts-rpc/pb"
)

type StsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStsServer
}

func NewStsServer(svcCtx *svc.ServiceContext) *StsServer {
	return &StsServer{
		svcCtx: svcCtx,
	}
}

func (s *StsServer) GetUserCosSts(ctx context.Context, in *pb.GetUserCosStsReq) (*pb.GetUserCosStsResp, error) {
	l := logic.NewGetUserCosStsLogic(ctx, s.svcCtx)
	return l.GetUserCosSts(in)
}
