// Code generated by goctl. DO NOT EDIT.
// Source: sts.proto

package stsrpc

import (
	"context"

	"github.com/xh-polaris/sts-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserCosStsReq  = pb.GetUserCosStsReq
	GetUserCosStsResp = pb.GetUserCosStsResp

	StsRpc interface {
		GetUserCosSts(ctx context.Context, in *GetUserCosStsReq, opts ...grpc.CallOption) (*GetUserCosStsResp, error)
	}

	defaultStsRpc struct {
		cli zrpc.Client
	}
)

func NewStsRpc(cli zrpc.Client) StsRpc {
	return &defaultStsRpc{
		cli: cli,
	}
}

func (m *defaultStsRpc) GetUserCosSts(ctx context.Context, in *GetUserCosStsReq, opts ...grpc.CallOption) (*GetUserCosStsResp, error) {
	client := pb.NewStsRpcClient(m.cli.Conn())
	return client.GetUserCosSts(ctx, in, opts...)
}
