// Code generated by goctl. DO NOT EDIT.
// Source: sts.proto

package sts

import (
	"context"

	"github.com/xh-polaris/sts-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserCosStsReq  = pb.GetUserCosStsReq
	GetUserCosStsResp = pb.GetUserCosStsResp

	Sts interface {
		GetUserCosSts(ctx context.Context, in *GetUserCosStsReq, opts ...grpc.CallOption) (*GetUserCosStsResp, error)
	}

	defaultSts struct {
		cli zrpc.Client
	}
)

func NewSts(cli zrpc.Client) Sts {
	return &defaultSts{
		cli: cli,
	}
}

func (m *defaultSts) GetUserCosSts(ctx context.Context, in *GetUserCosStsReq, opts ...grpc.CallOption) (*GetUserCosStsResp, error) {
	client := pb.NewStsClient(m.cli.Conn())
	return client.GetUserCosSts(ctx, in, opts...)
}
