// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: sts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StsClient is the client API for Sts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StsClient interface {
	GetUserCosSts(ctx context.Context, in *GetUserCosStsReq, opts ...grpc.CallOption) (*GetUserCosStsResp, error)
}

type stsClient struct {
	cc grpc.ClientConnInterface
}

func NewStsClient(cc grpc.ClientConnInterface) StsClient {
	return &stsClient{cc}
}

func (c *stsClient) GetUserCosSts(ctx context.Context, in *GetUserCosStsReq, opts ...grpc.CallOption) (*GetUserCosStsResp, error) {
	out := new(GetUserCosStsResp)
	err := c.cc.Invoke(ctx, "/sts.Sts/getUserCosSts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StsServer is the server API for Sts service.
// All implementations must embed UnimplementedStsServer
// for forward compatibility
type StsServer interface {
	GetUserCosSts(context.Context, *GetUserCosStsReq) (*GetUserCosStsResp, error)
	mustEmbedUnimplementedStsServer()
}

// UnimplementedStsServer must be embedded to have forward compatible implementations.
type UnimplementedStsServer struct {
}

func (UnimplementedStsServer) GetUserCosSts(context.Context, *GetUserCosStsReq) (*GetUserCosStsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCosSts not implemented")
}
func (UnimplementedStsServer) mustEmbedUnimplementedStsServer() {}

// UnsafeStsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StsServer will
// result in compilation errors.
type UnsafeStsServer interface {
	mustEmbedUnimplementedStsServer()
}

func RegisterStsServer(s grpc.ServiceRegistrar, srv StsServer) {
	s.RegisterService(&Sts_ServiceDesc, srv)
}

func _Sts_GetUserCosSts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCosStsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StsServer).GetUserCosSts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sts.Sts/getUserCosSts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StsServer).GetUserCosSts(ctx, req.(*GetUserCosStsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sts_ServiceDesc is the grpc.ServiceDesc for Sts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sts.Sts",
	HandlerType: (*StsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUserCosSts",
			Handler:    _Sts_GetUserCosSts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sts.proto",
}
